version: 0.2

env:
  variables:
    build_version: "0.1"

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - apt-get update
      - apt-get install software-properties-common build-essential -yy
      - apt-add-repository ppa:brightbox/ruby-ng
      - apt-get update
      - apt-get install rubygems ruby2.4 ruby2.4-dev ruby-switch -yy
      - ruby-switch --set ruby2.4
  pre_build:
    commands:
      - echo "Pre build steps"
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo "Runnings the tests"
      - bundle exec rspec
